### ISSUE TITLE
maps.txt is not created

### ISSUE THREAD

**Issue by mort1an** [partiusfabaa/cs2-MiniAdmin#13]
The plugin works great, the database is connected, the administrator is issued, but this map.txt file is not created, which is why, as I understand it, css_map does not work

**Comment by kus** [comment]
It would be nice if it created the file for you with the default maps from the mapcycle.txt (or just used the current mapcyclefile in CS:GO you could change it with `sm_cvar mapcyclefile`), but you can just create the `maps.txt` file yourself and put it here `/addons/counterstrikesharp/plugins/MiniAdmin/maps.txt`

You can put these defaults in it:

```
cs_italy
cs_office
de_ancient
de_anubis
de_dust2
de_inferno
de_mirage
de_nuke
de_overpass
de_vertigo
```

**Comment by mort1an** [comment]
Oh, I understand, thank you, I would like to add this information to the description of this plugin
