### ISSUE TITLE
can't kick / ban bcs. player not found (we used the good userid)

### ISSUE THREAD

**Issue by originalaidn** [partiusfabaa/cs2-MiniAdmin#16]
everything in the title

and please if you could, use admins from configs/admins.json

**Comment by partiusfabaa** [comment]
try this [version](https://github.com/partiusfabaa/cs2-MiniAdmin/releases/tag/v1.0.4.1).

**Comment by originalaidn** [comment]
i'll try it, but would you add search by playername and not userid?

**Comment by partiusfabaa** [comment]
no, not yet
