### ISSUE TITLE
Map is not changing

### ISSUE THREAD

**Issue by PorcusorulMagic** [partiusfabaa/cs2-MiniAdmin#18]
Hello! My friend tried  !map command and it doesn't work
![image-12](https://github.com/partiusfabaa/cs2-MiniAdmin/assets/98654600/4edffbd6-c9bc-42e0-93bd-38665b5b22f5)

**Comment by partiusfabaa** [comment]
First of all, did you write in maps.txt? Secondly - ws: prefix doesn't work for this admin

**Comment by PorcusorulMagic** [comment]
1.  Yes, i write all my workshop maps working on server
2. This plugin doesn't have workshop support? :(

**Comment by partiusfabaa** [comment]
> 1. Yes, i write all my workshop maps working on server
> 2. This plugin doesn't have workshop support? :(

No, not yet. But I will definitely make it in the new version. I don't know exactly when I'll release it. When it's possible to disable voice chat. I'll post it right away.
