### ISSUE TITLE
cant add admin

### ISSUE THREAD

**Issue by chycken** [partiusfabaa/cs2-MiniAdmin#20]
Hello, when I add an admin from webadmin console, then it says everythings fine (added), I can see the new admin on database, but when this player wants to open !admin, it says that he doesnt have permession .... Cssharp v53, tested on v54, and doesnt work...

**Comment by SuperCannabis** [comment]
Hi. What  exactly you're typing at the webadmin console? Cause for me it wont add me on database

**Comment by chycken** [comment]
Hi, css_addadmin "name" "steamid "time, 0=permanently"
Exp: css_addadmin "Chicken" "STEAM_1:1:66577778" "0"

**Comment by SuperCannabis** [comment]
![1](https://github.com/partiusfabaa/cs2-MiniAdmin/assets/151227232/46aea626-c331-49c6-ae61-614cb57f294a)
this what i got when i type in that format)

**Comment by partiusfabaa** [comment]
> Hello, when I add an admin from webadmin console, then it says everythings fine (added), I can see the new admin on database, but when this player wants to open !admin, it says that he doesnt have permession .... Cssharp v53, tested on v54, and doesnt work...

I apologize for not responding sooner. Can I know your steam id? You can remove a couple of digits, I just need STEAM_0:1:1.

**Comment by chycken** [comment]
![AAAAA](https://github.com/partiusfabaa/cs2-MiniAdmin/assets/25958225/7cdfbb37-7bdb-4459-965b-1fc48ecdabbc)
only the first working, i dont know why...Other guys when say !admin, it says they dont have permission...

**Comment by partiusfabaa** [comment]
> ![AAAAA](https://user-images.githubusercontent.com/25958225/284022223-7cdfbb37-7bdb-4459-965b-1fc48ecdabbc.png) only the first working, i dont know why...Other guys when say !admin, it says they dont have permission...

try replacing `STEAM_1:` with `STEAM_0:`

**Comment by partiusfabaa** [comment]
> yeah its working like this...Is this a bug or what?

No, it's just that in CSSharp the SteamId always goes STEAM_0: , that's why it's like this
