### ISSUE TITLE
Can you add al the command to chat-menu?

### ISSUE THREAD

**Issue by chycken** [partiusfabaa/cs2-MiniAdmin#21]
![asddd](https://github.com/partiusfabaa/cs2-MiniAdmin/assets/25958225/ca5ff6ce-de49-4611-9bf9-ec1dc1b31c2d)
Hello, can you add all the avaliable commands to the chat when an admin say !admin .. ? It shows only one (!1) ...

**Comment by partiusfabaa** [comment]
Because I haven't made the admin menu yet. As soon as there is an option to disable voice chat, I will post a new version right away

**Comment by chycken** [comment]
Hm, other plugins have it, like example discord report, weapon paints. in these plugins, when i say !command, it shows all opportunity

**Comment by partiusfabaa** [comment]
because they are implemented there. And in this version of the administration area I have not implemented them

**Comment by chycken** [comment]
oh understand. It would be grateful if you could do the same
