### ISSUE TITLE
need fix for css 101+

### ISSUE THREAD

**Issue by mrdiega** [partiusfabaa/cs2-MiniAdmin#26]
Mini Admin v1.0.4.1
css v110

When starting the server (with bots) and when a player connects, an error appears in the console:
`CSSharp: Native 57b77d8f was invoked on a non-main thread`

```
css_plugins list
  List of all plugins currently loaded by CounterStrikeSharp: 12 plugins loaded.
  [#1:LOADED]: "Mini Admin" (v1.0.4) by thesamefabius
  [#2:LOADED]: "Round End Bhop" (0.0.1)
  [#3:LOADED]: "Weapon Restrict" (1.2) by Quake1011
    Prohibits purchase or picking up restricted weapons
  [#4:LOADED]: "AFK Manager" (0.0.8) by NiGHT & K4ryuu
  [#5:LOADED]: "Force AllTalk" (1.1) by Fortis
    Enables all convar variables
  [#6:LOADED]: "Auto Balance Plugin" (0.4.2) by hTx
  [#7:LOADED]: "ResetScore" (v1.2.0) by CYBERC4T
  [#8:LOADED]: "WeaponPaints" (1.3d) by Nereziel & daffyy
    Skin and knife selector, standalone and web-based
  [#9:LOADED]: "Setbothp" (v2.0.0) by jackson tougher
  [#10:LOADED]: "CS2-Tags" (1.0.3) by daffyy
    Add player tags easily in cs2 game
  [#11:LOADED]: "AutoClearMaps" (v1.0.0) by CYBERC4T
  [#12:LOADED]: "Discord Relay" (1.0.0) by K4ryuu
```
If remove this plugin, then this error does not exist.

**Comment by lowoa** [comment]
+1

**Comment by partiusfabaa** [comment]
i think I'll release a new version today. With mute

**Comment by ghostss2016** [comment]
> i think I'll release a new version today. With mute

release please

**Comment by lowoa** [comment]
so when will the update be? 🥴

**Comment by partiusfabaa** [comment]
> > i think I'll release a new version today. With mute
> 
> release please



> so when will the update be? 🥴



I want to release updates very badly, but CSSharp hasn't taken a mute yet. I already have everything ready to go. Just have to wait for the mute to be accepted and I'll release the updates right away.

**Comment by lowoa** [comment]
oki, thank u

**Comment by partiusfabaa** [comment]
[theres a mute in this version!](https://github.com/partiusfabaa/cs2-MiniAdmin/releases/tag/v1.0.5) :)
