### ISSUE TITLE
[REQ] When a user without access uses the command, it shows instructions for using it

### ISSUE THREAD

**Issue by crashzk** [partiusfabaa/cs2-MiniAdmin#29]
It would be interesting to remove this feature. When the user, even without administrative access, uses a command, the plugin shows information on how the plugin should be used.

![image](https://github.com/partiusfabaa/cs2-MiniAdmin/assets/32937653/48670fa1-a3d8-4a03-a410-706c0014d272)

It would be possible to just leave the message that he does not have access to the command.

**Comment by partiusfabaa** [comment]
these are messages from cssharp

**Comment by crashzk** [comment]
Got it, so for now we can close this issue, thank you
