### ISSUE TITLE
Admin commands won't work

### ISSUE THREAD

**Issue by DennisSkov** [partiusfabaa/cs2-MiniAdmin#39]
I'm running the latest version of MetaMod:Source, CounterStrikeSharp and the plugin (1.0.5.5). I've added myself as an admin:
```
select * from miniadmin_admins;
+----+----------+--------------------+------------+----------+----------+-------+
| id | username | steamid            | start_time | end_time | immunity | flags |
+----+----------+--------------------+------------+----------+----------+-------+
|  6 | sNIP     | STEAM_1:0:37695864 | 1706705460 |        0 |      100 | z     |
+----+----------+--------------------+------------+----------+----------+-------+
```
Whenever I do any commands, I'm told I don't have permissions for that command. I can't even execute !admin. 
Is anything else required?

**Comment by partiusfabaa** [comment]
> I'm running the latest version of MetaMod:Source, CounterStrikeSharp and the plugin (1.0.5.5). I've added myself as an admin:
> 
> ```
> select * from miniadmin_admins;
> +----+----------+--------------------+------------+----------+----------+-------+
> | id | username | steamid            | start_time | end_time | immunity | flags |
> +----+----------+--------------------+------------+----------+----------+-------+
> |  6 | sNIP     | STEAM_1:0:37695864 | 1706705460 |        0 |      100 | z     |
> +----+----------+--------------------+------------+----------+----------+-------+
> ```
> 
> Whenever I do any commands, I'm told I don't have permissions for that command. I can't even execute !admin. Is anything else required?

try changing the steem id from `STEAM_1:0:37695864` to `STEAM_0:0:37695864`

**Comment by FightnightKidd** [comment]
didnt work for me either i changed steam id and try steamid64 still nothing

**Comment by DennisSkov** [comment]
> try changing the steamid from `STEAM_1:0:37695864` to `STEAM_0:0:37695864`

Worked, thanks.
