### ISSUE TITLE
addadmin, no permission, database ok

### ISSUE THREAD

**Issue by Apflesine** [partiusfabaa/cs2-MiniAdmin#44]
command used:
css_addadmin "APF" "STEAM_1:1:51074596" "100" "abcdefghijklmnoz" "0"

Database looks good!

![Screenshot_20240320_213014](https://github.com/partiusfabaa/cs2-MiniAdmin/assets/56201765/ac27bf02-c8de-4b55-9f9c-0387a73bd2c6)

tried restarting the server and rejoining several times
also tried different values for immunity flags and time

!admin results in: (also tried other commands)

![Screenshot_20240320_213312-1](https://github.com/partiusfabaa/cs2-MiniAdmin/assets/56201765/3fc87a1a-6935-4c87-9f94-9689b09ea54b)

**Comment by Apflesine** [comment]
I tried texting you on discord, but the message got deleted ...

**Comment by partiusfabaa** [comment]
> I tried texting you on discord, but the message got deleted ...

change `STEAM_1` to `STEAM_0`

**Comment by Apflesine** [comment]
worked! THX!
