### ISSUE TITLE
Unsure how to get the plugin working with mysql

### ISSUE THREAD

**Issue by Elektrosync** [partiusfabaa/cs2-MiniAdmin#47]
Hello, i recently got the plugin and i was able to set up some kind of database server through mysql, but every time i check no data was written to the database i assigned it too in mysql i think this is more my own fault not knowing how to use mysql is there any way you can help me?

**Comment by Elektrosync** [comment]
![Screenshot 2024-04-11 221856](https://github.com/partiusfabaa/cs2-MiniAdmin/assets/101218723/0caccb19-62c8-48e4-9395-61ee47205736)
I'm not sure if this might be the issue if its irrelevant let me know

**Comment by partiusfabaa** [comment]
Hello, the problem is in the config, line 11-12

**Comment by Elektrosync** [comment]
Thank you so much for your reply, i fixed the config and now everything works as it was intended
