### ISSUE TITLE
How to add admin

### ISSUE THREAD

**Issue by szogun1910** [partiusfabaa/cs2-MiniAdmin#8]
Hey, how to add myself to the list of administrators after a fresh installation, because the server returns the command information about the command unavailability

**Comment by partiusfabaa** [comment]
`css_addadmin "username" "steamid (example: STEAM_0:1:123456)" "time_minutes or 0 - permanently"`

**Comment by szogun1910** [comment]
I have seen this command only when I use it I get this message
[ MiniAdmin ] you do not have access to this command

**Comment by partiusfabaa** [comment]
must be written from the server console

**Comment by szogun1910** [comment]
ok, my blunder because I used the console with cs to do it
